config/routes.rb
Rails.application.routes.draw do
  root 'overview#index'
  get 'ping' => 'health_check#ping'
  get 'login' => 'sessions#new', as: :new_user_session
  scope :login do
    scope 'sso/:provider', controller: :o_auth, as: :oauth do
      root action: :begin, as: :login
      get :receive
      get :authenticate
    end
  end
  get 'auth_check' => 'sessions#validate'
  get 'logout' => 'sessions#destroy', as: :destroy_user_session
  resources :users, only: %i[index show update], constraints: {
    id: /[0-9]+/
  } do
    collection do
      resources :authorizations, only: %i[create destroy]
    end
  end
  scope :search, controller: :search, as: :search do
    get :results
    get :manifest
    get :suggestions
  end
  scope :install, controller: :install, as: :install do
    get 'oauth'
    post 'oauth', action: :create_provider
    get 'configure'
  end
  resources :certificates, only: %i[create index new show], constraints: {
    id: /[0-9]+/,
    another_id: /[0-9]+/
  } do
    member do
      get 'csr'
      get 'revocation_check'
      get 'chain'
      scope :sign, controller: :signing do
        scope :lets_encrypt, controller: :lets_encrypt do
          root action: :index, as: :lets_encrypt
          post :register
          get :prove_ownership
          post :start_import
        end
      end
      get 'sign/:another_id' => 'signing#configure'
      post 'sign/:another_id' => 'signing#sign_cert'
    end
    collection do
      get 'import'
      scope :import, controller: :import do
        get 'from_url', action: :from_url
        post 'from_url', action: :from_url
        post '', action: :do_import
      end
      post 'analyze'
    end
  end
  resources :acme_sign_attempts, only: %I[show destroy]
  resources :public_keys, only: %I[show]
  resources :services, constraints: {
    id: /[0-9]+/
  } do
    member do
      get 'deploy'
    end
    collection do
      get 'deployment'
    end
  end
  scope :private_keys, controller: :private_keys do
    post :analyze, as: :analyze_private_key
  end
  resource :settings, only: %i[show update] do
    member do
      post 'validate/mail_server', action: 'validate_mail_server'
    end
  end
  resources :agents, as: :agent, only: %I[new update] do
    collection do
      post :generate_token
    end
  end
  scope :agents, controller: :agents_api, as: :agent do
    get 'register/:token', action: :register, as: :register, constraints: {
      token: /([a-zA-Z0-9_\-]+\.?){3}/
    }
    post :bootstrap
    get :sync
    post :report
    get 'service/:id', action: :cert_chain, as: :service
  end
  scope :jobs, controller: :jobs, as: :jobs do
    get :refresh_all
    post :refresh_cert_bundle
  end
  get 'acme-challenge-responder/:token' => 'lets_encrypt#validate_token'

  # mount Resque::Server.new, at: '/resque'
end

app/models/service.rb
class Service < ApplicationRecord
  belongs_to :certificate

  class << self
    def service_props
      @service_props ||= Set.new
    end
  end

  def properties
    # This can't be the simplest way to do this
    s = super
    return s if s

    self.properties = {}
    super
  end

  def push_deployable?
    false
  end

  def deployable?
    certificate.signed?
  end

  def node_status
    rkey = "SERVICE_#{id}_NODESTATUS"
    redis = CertManager::Configuration.redis_client
    redis.hgetall(rkey).map { |_key, value|
      Node.new JSON.parse value
    }
  end

  def status
    status = node_status
    good = status.count(&:valid?)
    if status.count.zero?
      'Unknown'
    elsif good == status.count
      "Running [#{good}/#{status.count}]"
    else
      'Inconsistent'
    end
  end

  def model_name
    ActiveModel::Name.new(Service)
  end

  def self.service_prop(*properties)
    properties.each do |property|
      prop = property.to_s
      service_props << property
      define_method(property) do
        self.properties[prop]
      end
      define_method("#{property}=") do |value|
        self.properties[prop] = value
      end
    end
  end
end

app/models/service/rancher.rb
class Service::Rancher < Service
  service_prop :service_endpoint, :bearer_token
  service_prop :cluster_id, :project_id, :namespace, :rancher_cert_id

  def deploy
    HttpRequest.put(
      update_url, update_payload.to_json,
      content_type: 'application/json',
      auth: "Bearer #{bearer_token}",
      'Accept' => 'application/json'
    )
  rescue Faraday::ClientError => e
    body = JSON.parse(e.response[:body])
    message = "Rancher returned: #{body['message']}"
    ServiceDeployFailed.raise_faraday message, e
  end

  def push_deployable?
    true
  end

  def ui_link
    uri = URI(service_endpoint)
    uri.path = "/p/#{cluster_id}:#{project_id}/certificates/#{rancher_cert_id}"
    uri
  end

  private

  def update_payload
    {
      certs: cert_chain,
      key: certificate.private_key.to_pem,
      annotations: {
        'certs.technowizardry.net/service' => id
      }
    }
  end

  def cert_chain
    chain = certificate.chain.reverse.map do |cert|
      cert.public_key.to_pem
    end
    chain.join("\n")
  end

  def cert_uri_part
    if namespace.empty?
      'certificates'
    else
      'namespacedCertificates'
    end
  end

  def update_url
    uri = URI(service_endpoint)
    uri.path = "#{uri.path}/project/#{cluster_id}:#{project_id}/#{cert_uri_part}/#{rancher_cert_id}"
    uri
  end
end

app/models/service/salt.rb
class Service::Salt < Service
  service_prop :cert_path, :after_rotate, :node_group

  def deploy
    chain = certificate.full_chain(true)
    salt = SaltClient.new

    salt.stat_file(node_group, cert_path).each do |minion, stat|
      if stat
        Rails.logger << "#{minion}: File exists #{cert_path}"
        handle_result(salt.truncate_file(node_group, cert_path), 'truncate file')
      else
        Rails.logger << "#{minion}: Creating file #{cert_path}"
        salt.create_file(minion, cert_path)
      end
    end
    handle_result(salt.append_file(node_group, cert_path, chain), 'append_file')
    handle_result(salt.shell_execute(node_group, after_rotate), 'execute script')

    self.last_deployed = Time.now
  end

  private

  def handle_result(input, msg)
    input.each do |key, val|
      msg = (if val
               "Successfully #{msg} #{val}"
             else
               "Failed to #{msg} #{val}"
             end)
      Rails.logger << "#{key}: #{msg}"
    end
  end
end

app/models/service/soteria_agent.rb
class Service::SoteriaAgent < Service
  SIGNALS = %w[HUP USR1].sort.freeze
  has_many :memberships, class_name: 'AgentService', foreign_key: :service_id, inverse_of: :service
  has_many :agents, through: :memberships
  service_prop :cert_path, :rotate_enabled, :rotate

  # Validations
  validates :cert_path, presence: true
  # validates :signal, inclusion: { in: SIGNALS }
  validates :rotate, presence: true, if: :rotate_enabled

  def agent_ids
    agents.map(&:id)
  end

  def deployable?
    false
  end

  alias triggers_post_rotate? rotate_enabled

  def as_agent_manifest
    map = {
      id: id,
      path: cert_path,
      after_action: [],
      hash: {
        algorithm: :sha256,
        value: certificate.chain_hash
      }
    }

    if triggers_post_rotate?
      map[:after_action] << {
        type: :docker,
        container_name: rotate['container_name'],
        signal: rotate['signal']
      }
    end
    map
  end

  def agent_ids=(agents)
    agents = agents.dup
    memberships.each do |member|
      id = member.id.to_s
      if agents.key?(id)
        agents.remove id
      else
        member.delete
      end
    end
    agents.each_key do |id|
      memberships << AgentService.new(agent: Agent.find(id.to_i), service: self)
    end
  end
end

app/controllers/service_controller.rb
class ServiceController < ApplicationController
  def index
    @services = Service.all
  end

  def new
    @selected_cert_id = params[:cert_id].to_i || 0
  end

  def show
    @service = Service.find(params[:id])
  end

  def deploy
    service = Service.find(params[:id])
    job = DeployServiceJob.perform_later service
    redirect_to deployment_service_index_path(id: job.job_id)
  end

  def nodes
    salt = SaltClient.new
    salt.login
    render json: salt.get_minions("#{params[:query]}*")['return'].first.map {|k,v| k }
  end

  def create
    cert = Certificate.find(params[:certificate])
    service = Service.create(params.permit(:cert_path, :after_rotate, :node_group).merge({certificate: cert}))
    #service.certificate = cert
    service.save!
    redirect_to service
  end

  def deployment
    redis = CertManager::Configuration.redis_client
    service_id = redis.get("job_#{params[:id]}_service").to_i
    @log = redis.lrange("job_#{params[:id]}_log", 0, -1)
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  def index
    @services = Service.all.includes(:certificate)
    @agents = Agent.all
  end

  def new
    type = pick_service_type
    @service = type.new
    @service.certificate_id = params[:cert_id].to_i || 0
    flash[:error]&.each do |error|
      @service.errors.add error
    end
    case params[:type]
    when 'rancher'
      render 'services/rancher/new'
    else
      render 'services/new'
    end
  end

  def create
    raise NotSupported unless params[:service][:type].in? %w[Service::SoteriaAgent Service::Rancher]

    redirect_to Service.create! service_create_params
  rescue ActiveRecord::RecordInvalid => e
    flash[:error] = e.record.errors
    redirect_to action: :new
  end

  def edit
    @service = Service.find params[:id]
  end

  def show
    @service = Service.find params[:id]
    @node_status = @service.node_status
  end

  def update
    service = Service.find params[:id]
    u_params = service_update_params
    u_params[:agent_ids] = params[:service][:agent_ids] if params[:service].key? :agent_ids

    service.update! u_params
    redirect_to service
  end

  def deploy
    service = Service.find(params[:id])
    job = DeployServiceJob.perform_later service
    redirect_to deployment_services_path(id: job.job_id)
  end

  def destroy
    service = Service.find params[:id]
    service.destroy!
    redirect_to services_path
  end

  def deployment
    redis = CertManager::Configuration.redis_client
    @status = (redis.get("job_#{params[:id]}_status") || 0).to_i
    @log = redis.lrange("job_#{params[:id]}_log", 0, -1)
  end

  private

  def pick_service_type
    case params[:type]
    when 'rancher'
      Service::Rancher
    else
      Service::SoteriaAgent
    end
  end

  def service_create_params
    params.require(:service).permit(:type, service_any_params, rotate: %i[container_name signal])
  end

  def service_update_params
    params.require(:service).permit(:cert_path, service_any_params)
  end

  def service_any_params
    svc_params = Set.new([:certificate_id])
    Service::Rancher.service_props.each { |param| svc_params << param }
    Service::SoteriaAgent.service_props.each { |param| svc_params << param }
    svc_params.to_a
  end
end

app/helpers/service_helper.rb
module ServiceHelper
  def options_for_certificate_list(certs, selected = nil)
    options_for_select(certs.map { |cert|
      [cert.subject, cert.id, { data: { ca: cert.can_sign? } }]
    }, selected)
  end
end

app/views/services/_agent_status_table.html.haml
%h2 Worker agents
= link_to 'New agent', new_agent_path
%table.table
  %thead
    %tr
      %td Id
      %td Last synchronized
      %td Options
  %tbody
    - @agents.each do |agent|
      %tr{ class: ('bg-warning' if agent.last_sync_long_ago?) }
        %td= agent.id
        %td<
          - if agent.last_synced_at
            = time_ago_enhanced_block(agent.last_synced_at)
          - else
            Not synced

app/views/services/_edit_agent.html.haml
.form-group
  %label.control-label.col-sm-2{ for: 'service-cert-path' }= t 'activerecord.attributes.service.cert_path'
  .col-sm-10
    %input.form-control#service-cert-path{ type: :text, disabled: true, value: service.cert_path }
    %div= t 'activerecord.help.service.cert_path'
    .text-warn= t 'views.services.edit.agent.cert_path_note'
= f.fields_for :rotate do |r|
  = r.text_field :container_name, help: t('activerecord.help.service.rotate_container_name')
  = r.select :signal, Service::SoteriaAgent::SIGNALS, help: t('views.services.new.after_update.signal')

%ul
  - Agent.find_each do |agent|
    %li
      %label
        %input{ type: :checkbox, name: "service[agent_ids][#{agent.id}]" }
        %span= agent.last_hostname

app/views/services/_new_service_form.html.haml
= bootstrap_form_for service, url: services_path, layout: :horizontal do |f|
  .well
    %h3= t 'views.services.new.config.header'
    = f.select :certificate_id, options_for_certificate_list(Certificate.signed, service.certificate_id), help: t('views.services.new.help.certificate')
    = f.hidden_field :type, value: Service::SoteriaAgent.to_s
    = f.text_field :cert_path, label: 'File path', placeholder: '/etc/nginx/certs/example.com.pem', help: t('views.services.new.help.cert_path')
  .well
    %h3= t 'views.services.new.after_update.header'
    %p= t 'views.services.new.after_update.help'
    = f.fields_for :rotate do |r|
      .form-group
        %label.col-sm-2.control-label Post update
        .col-sm-10
          = f.check_box :rotate_enabled
      = r.text_field :container_name
      = r.select :signal, Service::SoteriaAgent::SIGNALS, help: t('views.services.new.after_update.signal')
  = f.submit 'Create service', class: 'btn btn-primary center-block'

app/views/services/_service_status.html.haml
%h3 Node Status
- bad_count = @node_status.count { |n| !n.valid? }
- if bad_count >= 1
  .bg-warning There #{'is'.pluralize bad_count} currently #{pluralize bad_count, 'inconsistent node'}.
  - if @service.deployable?
    %p= link_to 'Attempt to fix', deploy_service_path
%table.table
  %thead
    %tr
      %td= t 'views.services.show.table_headers.hostname'
      %td= t 'views.services.show.table_headers.status'
      %td= t 'views.services.show.table_headers.last_checked'
  %tbody
    - @node_status.each do |node|
      - if node.status.failed?
        - color = 'bg-danger'
      - elsif node.status.valid?
        - color = 'bg-success'
      %tr{ class: color }
        %td= node.hostname
        %td
          %div= t "views.services.show.statuses.#{node.status}"
          - if node.status.failed?
            %div= node.reason['message']
        %td= time_ago_enhanced_block node.updated_at

app/views/services/deployment.html.haml
- if @status <= 1
  - content_for :head do
    %meta{ content: 5, http: { equiv: 'refresh' } }
%h2 Deployment Log
.content-pane
  %ul
    - @log.each do |logg|
      %li= logg

app/views/services/edit.html.haml
%ol.breadcrumb
  %li= link_to 'Services', action: :index
  %li= link_to @service.certificate, service_path
  %li.active= t 'operations.edit'
%h2 Edit #{@service.certificate}
= bootstrap_form_for @service, layout: :horizontal do |f|
  - if @service.is_a? Service::SoteriaAgent
    = render partial: 'edit_agent', locals: { f: f, service: @service }
  - else
    - @service.class.service_props.each do |prop|
      = f.text_field prop
  = f.submit

app/views/services/index.html.haml
%ol.breadcrumb
  %li.active= link_to 'Services', action: :index
%h2 Your services
= link_to 'New service', action: :new
- if @services.empty?
  %p You haven't configuration any services yet. A service allows you to automatically deploy certificates to targets
- else
  %table.table
    %thead
      %tr
        %td Type
        %td Common Name
        %td Status
        %td Control
    %tbody
      - @services.each do |service|
        %tr{ class: ('bg-danger' if service.certificate.expires_in < 7.days) }
          %td= t "services.type.#{service.class.name.demodulize.downcase}"
          %td= link_to service.certificate.subject.CN, id: service.id, action: :show
          %td= service.status
          %td Refresh
= render partial: 'agent_status_table'

app/views/services/new.html.haml
- page_title 'New Service'
%ol.breadcrumb
  %li= link_to 'Services', action: :index
  %li.active New
%h2 Create service
.col-md-6
  = render partial: 'services/new_service_form', locals: { service: @service }
.col-md-6
  %h3= t 'views.services.new.deploy_plan.header'
  %p= t 'views.services.new.deploy_plan.help'
  = react_component 'pages/services/new/ServicesNewOverview', { certificateSelectId: 'service_certificate_id' }, prerender: true, data: { react_mount: true }

app/views/services/show.html.haml
- page_title "#{@service.certificate} Service"

%ol.breadcrumb
  %li= link_to 'Services', services_path
  %li.active= @service.certificate

= render partial: 'services/show/settings_pane'
%h1= @service.certificate
- if @service.deployable? && @service.last_deployed
  %p
    %span #{t 'views.services.show.last_deployed'}:
    = time_ago_enhanced_block @service.last_deployed

= link_to @service.certificate, certificate_path(@service.certificate)

- if @service.push_deployable?
  = link_to 'Deploy', deploy_service_path(service: @service)
- if @service.is_a? Service::Rancher
  = render partial: 'services/show/rancher_status', locals: { service: @service }
- else
  = render partial: 'services/show/service_status', locals: { node_status: @node_status }