config/routes.rb
Rails.application.routes.draw do
  root 'overview#index'
  get 'ping' => 'health_check#ping'
  get 'login' => 'sessions#new', as: :new_user_session
  scope :login do
    scope 'sso/:provider', controller: :o_auth, as: :oauth do
      root action: :begin, as: :login
      get :receive
      get :authenticate
    end
  end
  get 'auth_check' => 'sessions#validate'
  get 'logout' => 'sessions#destroy', as: :destroy_user_session
  resources :users, only: %i[index show update], constraints: {
    id: /[0-9]+/
  } do
    collection do
      resources :authorizations, only: %i[create destroy]
    end
  end
  scope :search, controller: :search, as: :search do
    get :results
    get :manifest
    get :suggestions
  end
  scope :install, controller: :install, as: :install do
    get 'oauth'
    post 'oauth', action: :create_provider
    get 'configure'
  end
  resources :certificates, only: %i[create index new show], constraints: {
    id: /[0-9]+/,
    another_id: /[0-9]+/
  } do
    member do
      get 'csr'
      get 'revocation_check'
      get 'chain'
      scope :sign, controller: :signing do
        scope :lets_encrypt, controller: :lets_encrypt do
          root action: :index, as: :lets_encrypt
          post :register
          get :prove_ownership
          post :start_import
        end
      end
      get 'sign/:another_id' => 'signing#configure'
      post 'sign/:another_id' => 'signing#sign_cert'
    end
    collection do
      get 'import'
      scope :import, controller: :import do
        get 'from_url', action: :from_url
        post 'from_url', action: :from_url
        post '', action: :do_import
      end
      post 'analyze'
    end
  end
  resources :acme_sign_attempts, only: %I[show destroy]
  resources :public_keys, only: %I[show]
  resources :services, constraints: {
    id: /[0-9]+/
  } do
    member do
      get 'deploy'
    end
    collection do
      get 'deployment'
    end
  end
  scope :private_keys, controller: :private_keys do
    post :analyze, as: :analyze_private_key
  end
  resource :settings, only: %i[show update] do
    member do
      post 'validate/mail_server', action: 'validate_mail_server'
    end
  end
  resources :agents, as: :agent, only: %I[new update] do
    collection do
      post :generate_token
    end
  end
  scope :agents, controller: :agents_api, as: :agent do
    get 'register/:token', action: :register, as: :register, constraints: {
      token: /([a-zA-Z0-9_\-]+\.?){3}/
    }
    post :bootstrap
    get :sync
    post :report
    get 'service/:id', action: :cert_chain, as: :service
  end
  scope :jobs, controller: :jobs, as: :jobs do
    get :refresh_all
    post :refresh_cert_bundle
  end
  get 'acme-challenge-responder/:token' => 'lets_encrypt#validate_token'

  # mount Resque::Server.new, at: '/resque'
end

app/models/certificate.rb
class Certificate < ApplicationRecord
  # Associations
  attr_accessor :issuer_subject
  belongs_to :issuer, class_name: 'Certificate', inverse_of: :sub_certificates, autosave: true
  has_many :sub_certificates, -> { where('certificates.issuer_id != certificates.id') }, class_name: 'Certificate', foreign_key: 'issuer_id'
  has_many :services
  has_many :acme_sign_attempts
  belongs_to :created_by, class_name: 'User'
  belongs_to :updated_by, class_name: 'User'
  belongs_to :private_key, autosave: true
  belongs_to :public_key, autosave: true
  belongs_to :subject, autosave: true
  belongs_to :inflight_acme_sign_attempt, class_name: 'AcmeSignAttempt'
  has_one :csr, class_name: 'CertificateSignRequest'
  accepts_nested_attributes_for :private_key
  accepts_nested_attributes_for :csr
  before_save :refresh_hash

  include HasPublicKey

  # Scopes
  scope :expiring_in, lambda { |time|
    now = Time.now
    joins(:public_key).where('public_keys.not_after < ? and public_keys.not_after > ?', now + time, now) if time.present?
  }
  scope :expired, -> { joins(:public_key).where('public_keys.not_after < ?', Time.now) }
  scope :owned, -> { where('certificates.private_key_id IS NOT NULL') }
  scope :signed, -> { where('certificates.private_key_id IS NOT NULL') }
  scope :leaf, -> { where('(SELECT COUNT(*) FROM certificates AS sub WHERE sub.issuer_id = certificates.id) == 0') }
  scope :with_subject, ->(subject) { joins(:subject).where(subjects: Subject.filter_params(subject.to_h)) }
  scope :with_everything, -> { eager_load(:private_key, public_key: :subject) }
  scope :can_sign, -> { joins(:public_key).where(public_keys: { is_ca: true }) }
  scope :for_public_key, lambda { |pub|
    joins(:private_key).where('private_keys.fingerprint = ?', pub.fingerprint)
  }
  scope :for_private_key, lambda { |pub|
    joins(:public_key).where('public_keys.fingerprint = ?', pub.fingerprint)
  }
  scope :deployed_with_service, -> { joins(:services).where('services.id IS NOT NULL') }

  def status
    if private_key.present? && public_key.present?
      'Signed'
    elsif private_key.present?
      'Unsigned'
    elsif public_key.present?
      'Public Only'
    else
      'Stub'
    end
  end

  def to_csr
    csr || public_key.csr
  end

  def domain_names
    ([subject.CN] + subject_alternate_names).uniq
  end

  def subject
    base = public_key || csr
    return base.subject if base

    'Private Key'
  end

  def in_trust_store
    chain.map(&:public_key).map(&:certificate_bundles).map(&:all).flatten.uniq
  end

  def generate_csr
    CertificateSignRequest.from_cert self
  end

  def public_keys
    PublicKey.where subject_id: public_key.subject_id
  end

  def to_s
    subject.to_s || 'No Subject'
  end

  def to_h
    hash = {
      id: id,
      subject: subject.to_h.stringify_keys
    }
    hash[:public_key] = public_key.to_h if public_key
    hash[:private_key] = private_key.to_h
    hash[:crl_endpoints] = crl_endpoints if crl_endpoints
    hash
  end

  delegate :as_json, to: :to_h

  def full_chain(include_private = false)
    chain = ''
    chain += "#{private_key.to_pem}\n" if include_private && private_key.present?
    chain += "#{public_key.to_pem}\n" if public_key
    chain += issuer.full_chain(false) if issuer_id.present? && issuer_id != id
    chain
  end

  def chain
    [*(issuer.chain if issuer.present? && issuer_id != id)] + [self]
  end

  def new_csr
    CertificateSignRequest.from_cert self
  end

  def sign(cert)
    # raise 'Must be a CA cert to sign other certs' unless public_key.is_ca? || public_key == cert.public_key
    # raise 'Basic constraints must include keyCertSign' unless public_key.key_usage.include? :keyCertSign
    cert.public_key.issuer_subject = subject
    cert.issuer = self
    ossl = cert.public_key.to_openssl
    ossl.issuer = subject.to_openssl
    ossl.public_key = cert.private_key.to_openssl.public_key
    ossl.sign private_key.to_openssl, public_key.hash_algorithm
    cert.public_key.body = ossl.to_der
    cert
  end

  def touch_by(user)
    self.created_by_id = user.id unless created_by_id
    self.updated_by_id = user.id
  end

  def touch_by!(user)
    touch_by user
    save!
  end

  def self.new_stub(subject)
    cert = Certificate.new
    cert.subject = Subject.from_r509(subject)
    cert
  end

  def self.find_for_key_pair(pub, priv)
    cert1 = Certificate.find_by(public_key_id: pub.id) if pub
    cert2 = Certificate.find_by(private_key_id: priv.id) if priv
    cert3 = Certificate.find_by(subject_id: pub.subject.id) if pub
    cert = cert1 || cert2 || cert3
    unless cert
      if pub
        cert = Certificate.joins(:private_key).find_by(private_keys: { fingerprint: pub.fingerprint })
      elsif priv
        cert = Certificate.joins(:public_key).find_by(public_keys: { fingerprint: priv.fingerprint })
      end
    end
    cert ||= Certificate.new
    cert.public_key = pub if pub
    cert.private_key = priv if priv
    cert
  end

  def self.import(crt)
    r509 = R509::Cert.new(cert: crt)
    cert = Certificate.with_subject(r509.subject).first
    cert = Certificate.new if cert.nil?
    cert.public_key = PublicKey.import(crt)
    cert.subject = cert.public_key.subject
    cert
  end

  private

  def refresh_hash
    self.chain_hash = Digest::SHA256.hexdigest(full_chain(true))
  end
end

app/controllers/certificate_controller.rb
include CrlHelper

class CertificateController < ApplicationController
  before_action :require_login

  def index
    @certs = Certificate.all.joins(:public_key).includes(:subject, :subject_alternate_names, :public_key)
    @expiring = Certificate.expiring_in(7.days)
  end

  def show
    @cert = Certificate.find(params[:id])
    respond_to do |format|
      format.pem {
        render plain: @cert.public_key.to_pem
      }
      format.html {
        if @cert.public_key
          render 'show'
        elsif @cert.stub?
          render 'show_stub'
        else
          render 'show_csr'
        end
      }
      format.json {
        render json: @cert
      }
    end
  end

  def new
  end

  def chain
    @cert = Certificate.find(params[:id])
    respond_to do |format|
      format.pem {
        render plain: @cert.chain.map {|cert|
          cert.public_key.body
        }.join()
      }
    end
  end

  def create
    private_key = R509::PrivateKey.new bit_length: params[:bit_length].to_i
    subject_model = Subject.create(subject_params)
    cert = Certificate.new
    cert.subject = subject_model
    cert.private_key_data = private_key.to_pem
    cert.save!

    redirect_to cert
  end

  def csr
    @cert = Certificate.find(params[:id])
    @csr = R509::CSR.new key: @cert.private_key, subject: @cert.subject.to_r509
    render 'csr/show'
  end

  def revocation_check
    cert = Certificate.find(params[:id])
    result = CrlHelper.check_status(cert)
    result << OcspFetcher.fetch_ocsp('http://ocsp.comodoca.com/', cert)

    respond_to do |format|
      format.json {
        render plain: result.to_json
      }
    end
  end

  def sign_cert
    @signee = Certificate.find(params[:another_id])
    if @signee.signer then
      render 'already_signed'
    else
      @signer = Certificate.find(params[:id])
      @allow_subject_changes = @signer != @signee
      @lifetime = 1.year
      @subject = @signee.subject
      @hash_algorithm = CertManager::SecurityPolicy.hash_algorithm.default
    end
  end

  def do_sign_cert
    @signer = Certificate.find(params[:id])
    @signee = Certificate.find(params[:another_id])
    @allow_subject_changes = @signer != @signee
    @lifetime = 1.year
    @subject = if params[:subject]
      Subject.create subject_params
    else
      @signee.subject
    end
    @hash_algorithm = params[:hash_algorithm] || CertManager::SecurityPolicy.hash_algorithm.default
    @csr = R509::CSR.new key: @signee.private_key,
      subject: @subject.to_r509,
      message_digest: @hash_algorithm

    cert = if @signer.id == @signee.id
      R509::CertificateAuthority::Signer.selfsign(csr: @csr)
    else
      ca = R509::CertificateAuthority::Signer.new(ca_cert: {
        cert: @signer.public_key.to_r509,
        key: (R509::PrivateKey.new key: @signer.private_key_data)
      })
      ca.sign(csr: @csr)
    end
    render plain: cert
  end

  def do_import
    certs = CertificateTools.extract_certificates(params[:key])
    keys = CertificateTools.extract_private_keys(params[:key])

    certs.uniq!
    # Welcome to hell
    @certs = certs.map {|cert2|
      cert3 = R509::Cert.new cert: cert2
      cert = Certificate.import cert2
      cert.issuer_subject = cert3.issuer
      cert.save!
      cert
    }
    keys.each { |key|
      pkey = R509::PrivateKey.new key: key
      cert = @certs.find {|c|
          c.public_key.modulus_hash == Digest::SHA1.hexdigest(pkey.key.params['n'].to_s) if c.public_key
        } #c.Certificate.with_modulus(key.key.params['n']).first
      if cert.present?
        cert.private_key_data = pkey.to_pem
      end
    }
    ActiveRecord::Base.transaction do
      @certs.each { |cert|
        if cert.issuer.nil?
          issuer = Certificate.find_by_subject(cert.issuer_subject).first
          if issuer.present?
            cert.issuer = issuer
          else
            cert.issuer = Certificate.new_stub(cert.issuer_subject)
          end
        end
        cert.save!
      }
    end
    if params[:return_url]
      redirect_to params[:return_url]
    else
      render 'import_done'
    end
  end

  private
  def subject_params
    params[:subject].permit(:O, :OU, :C, :CN) if params[:subject]
  end
end

app/controllers/certificates_controller.rb
class CertificatesController < ApplicationController
  def index
    query = CertificateFilter.new params.permit(:query, :page, :issuer, :expiring_in, :with_private_key)
    query.order_by_cn
    @certs = query.to_results
    @expiring = [] # @certs.expiring_in(30.days).order('not_after asc')
  end

  def show
    @cert = Certificate.eager_load(:public_key, :private_key).includes(:services).find(params[:id])
    self.model_id = @cert.id
    respond_to do |format|
      format.pem {
        render body: @cert.public_key.to_pem, content_type: Mime::Type.lookup_by_extension(:pem)
      }
      format.der {
        render body: @cert.public_key.to_der, content_type: Mime::Type.lookup_by_extension(:der)
      }
      format.html {
        if @cert.public_key
          render 'show'
        elsif @cert.stub?
          render 'show_stub'
        else
          @sign_candidates = Certificate.owned.signed.can_sign
          render 'show_csr'
        end
      }
      format.yaml {
        render plain: @cert.to_h.stringify_keys.to_yaml
      }
      format.json {
        render json: @cert
      }
      format.text {
        render text: @cert.public_key.to_text
      }
    end
  end

  def chain
    cert = Certificate.eager_load(:public_key, :private_key).find(params[:id])
    respond_to do |format|
      format.pem {
        render plain: cert.chain.map { |item|
          item.public_key.to_pem
        }.join("\n")
      }
      format.json {
        render json: cert.chain
      }
    end
  end

  def create
    cert = Certificate.new certificate_params
    cert.csr.private_key = cert.private_key
    cert.touch_by! current_user

    redirect_to cert
  end

  def csr
    id = params[:id]
    @csr = CertificateSignRequest.find_by certificate_id: id
    @csr ||= CertificateSignRequest.from_cert(Certificate.find(id))
    render 'csr/show'
  end

  def analyze
    cert = PublicKey.import request.body.read
    respond_to do |format|
      format.json {
        render json: cert.to_h
      }
      format.text {
        render plain: cert.to_text
      }
      format.yaml {
        render plain: cert.to_yaml
      }
    end
  end

  private

  def certificate_params
    params.require(:certificate)
          .permit(csr_attributes: [subject_alternate_names: [], subject_attributes: %i[O OU S C CN L ST]],
                  private_key_attributes: %i[bit_length type curve_name])
  end
end

app/helpers/certificate_helper.rb
module CertificateHelper
  def extract_certificates(input)
    parts = []
    part = ''
    input.lines.each { |line|
      part = part + line
      if line.starts_with?('-----END')
        if line.include?('CERTIFICATE')
          parts.push(R509::Cert.new cert: part)
        elsif line.include?('PRIVATE KEY')
          #parts.push(R509::PrivateKey.new key: part)
        else
          parts.push(part)
        end
        part = ''
      end
    }
    parts
  end
  def extract_private_keys(input)
    parts = []
    part = ''
    input.lines.each { |line|
      part = part + line
      if line.starts_with?('-----END')
        if line.include?('CERTIFICATE')
          #parts.push(R509::Cert.new cert: part)
        elsif line.include?('PRIVATE KEY')
          parts.push(R509::PrivateKey.new key: part)
        else
          parts.push(part)
        end
        part = ''
      end
    }
    parts
  end
  def find_private_key_for(cert, keys)
    modulus = cert.public_key.modulus
    keys.first { |key|
      key.is_a?(R509::PrivateKey) and key.key.modulus == modulus
    }
  end
end

app/views/certificates/_certificate_list.html.haml
%table.table.table-hover.table-condensed
  %thead
    %tr
      %td{ scope: 'col' } Common Name
      %td{ scope: 'col' } Status
      %td{ scope: 'col' } Expiration
  %tbody
    = render partial: 'certificates/certificate_row', collection: expiring, as: :cert
    = render partial: 'certificates/certificate_row', collection: certs, as: :cert
- if @certs.respond_to? :page
  .row
    .center-block.col-md-3= will_paginate certs

app/views/certificates/_certificate_row.html.haml
%tr{ class: ('bg-danger' if cert.expired? || cert.expires_in < 30.days) }
  %td
    = link_to cert, cert
    - if cert.expired?
      %span (expired #{time_ago_in_words(cert.public_key.not_after)} ago)
    - elsif cert.expires_in < 30.days
      %span (expires in #{time_ago_in_words(cert.public_key.not_after)})
    - if cert.subject_alternate_names.any?
      %span.visible-xs-block.visible-sm-inline.visible-md-inline.visible-lg-inline (+#{cert.subject_alternate_names.size} alternates)
  %td= cert.status
  %td<
    - if cert.expired?
      Expired
    - elsif cert.signed?
      = time_ago_in_words(cert.public_key.not_after)

app/views/certificates/_import_by_text_form.html.haml
%h3 Import from PEM
%p Import one or more certificates by pasting the the raw Base64-encoded data below
%div{ data: { drop: { type: :textbox, target: :key } } }
  = bootstrap_form_for :certificate, url: url_for(action: :import) do |f|
    .import-box#import-box-attach= react_component 'pages/certificates/import/CertificateImportContainer', {}, prerender: true, data: { react_mount: true }
    = f.submit 'Import certificate', class: 'btn btn-primary'

app/views/certificates/_subject.html.haml
%ul.subject
  - subject.attributes.each do |attrib|
    - if attrib[1].present? && attrib[0] != 'id'
      %li
        %div= attrib[1]
        %label= t("subject.#{attrib[0]}")

app/views/certificates/_validator.html.haml
%table.table.table-condensed
  %tbody
    = cert_show_validate_result public_key.not_before < Time.now, 'Valid from' do
      - public_key.not_before.in_time_zone(current_user.time_zone).to_s :long
    = cert_show_validate_result public_key.not_after > Time.now, 'Valid until' do
      - public_key.not_after.in_time_zone(current_user.time_zone).to_s :long
    - if public_key.bit_length
      = cert_show_validate_policy(:bit_length, public_key.bit_length, 'Bit Length') do
        - "#{public_key.bit_length} bits"
    - hash_algo = public_key.hash_algorithm
    = cert_show_validate_policy(:hash_algorithm, hash_algo, t('attributes.hash_algorithm')) do
      - t "hash.#{hash_algo}"
    %tr
      %td Subject Alternate Names
      %td= public_key.subject_alternate_names

app/views/certificates/import.html.haml
:ruby
  # Loading Indicator
  svg = <<~SVG
    M10,50c0,0,0,0.5,0.1,1.4c0,0.5,0.1,1,0.2,1.7c0,0.3,0.1,0.7,0.1,1.1c0.1,0.4,0.1,
    0.8,0.2,1.2c0.2,0.8,0.3,1.8,0.5,2.8 c0.3,1,0.6,2.1,0.9,3.2c0.3,1.1,0.9,2.3,1.4,3.5c0.5,1.2,1.2,2.4,1.8,3.7c0.3,0.6,
    0.8,1.2,1.2,1.9c0.4,0.6,0.8,1.3,1.3,1.9 c1,1.2,1.9,2.6,3.1,3.7c2.2,2.5,5,4.7,7.9,6.7c3,2,6.5,3.4,10.1,4.6c3.6,1.1,
    7.5,1.5,11.2,1.6c4-0.1,7.7-0.6,11.3-1.6 c3.6-1.2,7-2.6,10-4.6c3-2,5.8-4.2,7.9-6.7c1.2-1.2,2.1-2.5,3.1-3.7c0.5-0.6,
    0.9-1.3,1.3-1.9c0.4-0.6,0.8-1.3,1.2-1.9 c0.6-1.3,1.3-2.5,1.8-3.7c0.5-1.2,1-2.4,1.4-3.5c0.3-1.1,0.6-2.2,0.9-3.2c0.2-1,
    0.4-1.9,0.5-2.8c0.1-0.4,0.1-0.8,0.2-1.2 c0-0.4,0.1-0.7,0.1-1.1c0.1-0.7,0.1-1.2,0.2-1.7C90,50.5,90,50,90,50s0,0.5,0,1.4c0,
    0.5,0,1,0,1.7c0,0.3,0,0.7,0,1.1 c0,0.4-0.1,0.8-0.1,1.2c-0.1,0.9-0.2,1.8-0.4,2.8c-0.2,1-0.5,2.1-0.7,3.3c-0.3,1.2-0.8,2.4-1.2,
    3.7c-0.2,0.7-0.5,1.3-0.8,1.9 c-0.3,0.7-0.6,1.3-0.9,2c-0.3,0.7-0.7,1.3-1.1,2c-0.4,0.7-0.7,1.4-1.2,2c-1,1.3-1.9,2.7-3.1,4c-2.2,
    2.7-5,5-8.1,7.1 c-0.8,0.5-1.6,1-2.4,1.5c-0.8,0.5-1.7,0.9-2.6,1.3L66,87.7l-1.4,0.5c-0.9,0.3-1.8,0.7-2.8,1c-3.8,1.1-7.9,1.7-11.8,
    1.8L47,90.8 c-1,0-2-0.2-3-0.3l-1.5-0.2l-0.7-0.1L41.1,90c-1-0.3-1.9-0.5-2.9-0.7c-0.9-0.3-1.9-0.7-2.8-1L34,87.7l-1.3-0.6
    c-0.9-0.4-1.8-0.8-2.6-1.3c-0.8-0.5-1.6-1-2.4-1.5c-3.1-2.1-5.9-4.5-8.1-7.1c-1.2-1.2-2.1-2.7-3.1-4c-0.5-0.6-0.8-1.4-1.2-2
    c-0.4-0.7-0.8-1.3-1.1-2c-0.3-0.7-0.6-1.3-0.9-2c-0.3-0.7-0.6-1.3-0.8-1.9c-0.4-1.3-0.9-2.5-1.2-3.7c-0.3-1.2-0.5-2.3-0.7-3.3
    c-0.2-1-0.3-2-0.4-2.8c-0.1-0.4-0.1-0.8-0.1-1.2c0-0.4,0-0.7,0-1.1c0-0.7,0-1.2,0-1.7C10,50.5,10,50,10,50z
  SVG
.well.well-lg
  %h3= t('views.certificates.import.from_url.header')
  %p= t('views.certificates.import.from_url.sub_header')
  = form_tag import_certificates_path, class: 'form-inline' do
    .form-group
      = text_field_tag :host, nil, id: 'import-url', class: 'form-control',
        placeholder: t('views.certificates.import.from_url.url_placeholder'),
        aria: { label: t('views.certificates.import.from_url.url_aria_label') }
      = submit_tag t('operations.import'), id: 'import-button', class: 'btn'
    %svg.hidden.loading-indicator#import-indicator{ preserveaspectratio: 'xMidYMid', viewbox: '0 0 100 100', xmlns: 'http://www.w3.org/2000/svg' }
      %defs
        %filter#uil-ring-shadow{ height: '300%', width: '300%', x: '-100%', y: '-100%' }
          %feoffset{ dx: '0', dy: '0', in: 'SourceGraphic', result: 'offOut' }
          %fegaussianblur{ in: 'offOut', result: 'blurOut', stddeviation: '0' }
          %feblend{ in: 'SourceGraphic', in2: 'blurOut', mode: 'normal' }
      %path.loading-indicator-spinner{ d: svg, filter: 'url(#uil-ring-shadow)' }
.well.well-lg
  = render partial: 'import_by_text_form'
.well.well-lg
  %h3 Import certificate bundle
  %p Imports a third-party trusted certificate bundle such as the Firefox certificate store.
  = form_tag jobs_refresh_cert_bundle_path do
    = hidden_field_tag :bundle_class, CertificateBundle::Firefox.to_s
    = submit_tag 'Import', class: 'btn btn-default'

app/views/certificates/index.html.haml
%ul.nav.nav-pills
  %li.active= link_to (t 'certificate'), certificates_path, aria: { hidden: true }
  %li= link_to (t 'operations.import'), import_certificates_path, aria: { label: t('models.certificate.actions.import') }
  %li= link_to (t 'operations.new'), new_certificate_path, aria: { label: t('models.certificate.actions.new') }
%h2= t 'views.certificates.index.your_certificates'
%form{ action: certificates_path, method: 'GET' }
  %label
    %input{ type: 'checkbox', name: 'with_private_key', checked: params[:with_private_key] == 'on', value: 'on' }
    %span= t 'views.certificates.index.search.show_only_signed'
  %button{ type: :submit }= t 'views.certificates.index.search.submit'
= render partial: 'certificate_list', locals: { expiring: @expiring, certs: @certs }

app/views/certificates/show.html.haml
- page_title @cert.subject
%ol.breadcrumb
  = cert_chain_tree(@cert) do |cert|
    - if cert == @cert || cert.stub?
      %li.active= cert
    - else
      %li= link_to cert, cert
%h1= @cert.subject.CN
= render partial: 'validity_bar', locals: { cert: @cert }
%h4 Quick check
%ul
  - if @cert.can_sign?
    %li Can sign other certificates
  - else
    %li Can't sign other certificates
  - if @cert.expired?
    %li Expired
  - stores = @cert.in_trust_store
  - if stores.any?
    %li
      %span Anchored to trusted certificate
      %ul
        - stores.each do |store|
          %li= store.name
%aside
  %ul
    %li= react_component 'CertBodyDialogLink', { model: { id: @cert.id, type: 'Certificate' }, children: 'Show certificate' }, prerender: true, data: { react_mount: true }
    - if @cert.private_key
      %li= link_to 'Renew manually', action: :csr
      %li= link_to t('views.certificates.show.renew.lets_encrypt'), lets_encrypt_certificate_path
    %li= link_to pluralize(@cert.sub_certificates.count, 'child'), action: :index, issuer: @cert.id
= render partial: 'validator', locals: { public_key: @cert.public_key }
= render partial: 'certificates/history/history', locals: { cert: @cert }
%h2 Services
- if @cert.services.any?
  %ul
    - @cert.services.each do |service|
      %li= link_to service, service
- else
  %p No services yet. A service allows you to securely deploy this certificate to a host
  = link_to 'Create a service', controller: :services, action: :new, cert_id: @cert.id
#modal

app/views/certificates/show_csr.html.haml
%h1= @cert
- if @cert.inflight_acme_sign_attempt
  = render partial: 'certificates/acme/import_inprogress_banner', locals: { cert: @cert }
%p Unsigned certificate. This certificate has no issuer.
%h4 Sign this certificate
%ul
  %li
    %h5 Use external certificate authority
    %p Create a certificate signing request that can be submitted to an external party to be signed
    = link_to 'Generate CSR', action: :csr
  %li
    %h5 Let's encrypt
    %p Sign the certificate for free using Let's encrypt
    = link_to 'Sign', lets_encrypt_certificate_path
  %li
    %h5 Sign with existing private key
    %p If you already have a certificate capable of signing other certificates, you can sign this certificate without going to an external party
    %ul
      - @sign_candidates.each do |cert|
        %li= link_to cert, controller: :signing, action: :configure, id: cert, another_id: @cert
  %li
    %h5 Self sign
    %p This certificate won't be trusted by any clients by default. Use this if you want a basic certificate or a custom certificate authority
    = link_to 'Self Sign', controller: :signing, action: :configure, another_id: @cert.id

app/views/certificates/show_stub.html.haml
%h1= @cert.subject
.bg-warning
  %p This certificate is a stub and does not contain any public or private key data. As such no detailed data can be shown
  %p Please import the key to view more data.
  %p The only thing we know about the certificate is the subject:
= render partial: 'subject', locals: { subject: @cert.subject }